---
# yaml-language-server: $schema=https://schemas.tholinka.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &app plex
  namespace: external
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/group: Media
    gethomepage.dev/name: Plex
    gethomepage.dev/icon: plex.svg
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/widget.type: plex
    gethomepage.dev/widget.url: http://${PLEX_IP}:32400
    gethomepage.dev/widget.key: '{{HOMEPAGE_VAR_PLEX_TOKEN}}'
spec:
  hostnames:
    - 'plex.${SECRET_DOMAIN}'
  parentRefs:
    - name: external
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: *app
          port: 32400
      matches:
        - path:
            type: PathPrefix
            value: /
