---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: &name bitwarden
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      auth:
        secretRef:
          credentials:
            key: machine_access_token
            name: *name
            namespace: &namespace external-secrets
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: *namespace
        key: ca.crt
      organizationID: 954ba461-2dcd-41b7-a73d-b30b0145a152
      projectID: b404372f-38ee-48f0-b66a-b30c00ab0414
