---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
# this secret gets manually created at bootstrap, and then this takes control of it
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name bitwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: *name
  target:
    name: bitwarden-secret
    template:
      data:
        # this can NOT end in a newline or it doesn't work
        token: '{{ .token }}'
  data:
    - secretKey: token
      remoteRef:
        key: machine_access_token