---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app frigate
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    mode: enabled
  values:
    controllers:
      *app :
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: 0.16.1
            env:
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: *app
            resources:
              requests:
                cpu: 1000m
                memory: 2Gi
            securityContext:
              privileged: true

    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: go2rtc-streams.${SECRET_DOMAIN}
          lbipam.cilium.io/ips: 192.168.1.249
        ports:
          http:
            port: &port 8971
          unsecure:
            port: 5000
          rtsp:
            port: 8554
          webrtc-tcp:
            port: 8555
            protocol: TCP
          webrtc-udp:
            port: 8555
            protocol: UDP
          go2rtc:
            port: 1984
            protocol: TCP

    route:
      app:
        hostnames:
          - '{{ .Release.Name }}.${SECRET_DOMAIN}'
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
        annotations:
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/name: Frigate
          gethomepage.dev/group: Home
          gethomepage.dev/icon: frigate.svg
          gethomepage.dev/widget.type: frigate
          gethomepage.dev/widget.url: http://frigate.self-hosted.svc.cluster.local:5000

    persistence:
      data:
        existingClaim: *app
      config-file:
        enabled: true
        type: configMap
        name: frigate-configmap
        globalMounts:
          - path: /config/config.yml
            subPath: config.yaml
      media:
        type: nfs
        server: ${NAS_IP}
        path: ${NAS_PATH}/frigate
        globalMounts:
          - path: /media
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 4Gi
        globalMounts:
          - path: /dev/shm
