---
- Communicate:
  - Discord:
      - icon: discord.png
        href: 'https://discord.com/app'
  - Gmail:
      - icon: gmail.png
        href: 'http://gmail.com'
  - Google Calendar:
      - icon: google-calendar.png
        href: 'https://calendar.google.com'
  - Outlook:
      - icon: https://raw.githubusercontent.com/LilDrunkenSmurf/k3s-home-cluster/main/icons/outlook.png
        href: 'https://outlook.com'
- Media:
  - YouTube:
      - icon: youtube.png
        href: 'https://youtube.com/feed/subscriptions'
  - Spotify:
      - icon: spotify.png
        href: 'http://open.spotify.com'
  - Youtube Music:
      - icon: https://raw.githubusercontent.com/LilDrunkenSmurf/k3s-home-cluster/main/icons/youtube-music.png
        href: 'https://music.youtube.com'
- Reading:
  - Beyond:
      - icon: https://raw.githubusercontent.com/LilDrunkenSmurf/k3s-home-cluster/main/icons/beyond.png
        href: 'https://forums.beyond.ca/search.php?do=getnew&contenttype=vBForum_Post'
  - Reddit:
      - icon: reddit.png
        href: 'https://reddit.com'
- Git:
  - axeII/home-ops:
      - icon: github.png
        href: 'https://github.com/axeII/home-ops'
  - binaryn3xus/HomeOps:
      - icon: github.png
        href: 'https://github.com/binaryn3xus/HomeOps'
  - bjw-s/home-ops:
      - icon: github.png
        href: 'https://github.com/bjw-s/home-ops'
  - bo0tzz/kube:
      - icon: github.png
        href: 'https://github.com/bo0tzz/kube'
  - buroa/k8s-gitops:
      - icon: github.png
        href: 'https://github.com/buroa/k8s-gitops'
  - joryirving/home-ops:
      - icon: github.png
        href: 'https://github.com/joryirving/home-ops'
  - k8s-at-home:
      - icon: kubernetes-dashboard.png
        href: 'https://nanne.dev/k8s-at-home-search/'
  - LilDrunkenSmurf/k3s-home-cluster:
      - icon: github.png
        href: 'https://github.com/LilDrunkenSmurf/k3s-home-cluster'
  - mchestr/home-cluster:
      - icon: github.png
        href: 'https://github.com/mchestr/home-cluster'
  - onedr0p/home-ops:
      - icon: github.png
        href: 'https://github.com/onedr0p/home-ops'
  - szinn/k8s-homelab:
      - icon: github.png
        href: 'https://github.com/szinn/k8s-homelab'
  - timtorChen/homelab:
      - icon: github.png
        href: 'https://github.com/timtorChen/homelab'
  - TorStava/home-ops:
      - icon: github.png
        href: 'https://github.com/TorStava/home-ops'
