---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kavita
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/replicas]
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      kavita:
        pod:
          securityContext:
            runAsNonRoot: true
            fsGroup: 568
            runAsGroup: 568
            runAsUser: 568
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: RuntimeDefault }
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: ghcr.io/kareadita/kavita
              tag: 0.8.7@sha256:b9c671586db2a6a688da3cb4b45f1319cca33b01e6e760c8bf3c19d60101bdf2
            resources:
              requests:
                cpu: 15m
                memory: 512Mi
              limits:
                memory: 2Gi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ['ALL'] }

    service:
      app:
        ports:
          http:
            port: 5000
    route:
      app:
        hostnames:
          - '{{ .Release.Name }}.${SECRET_DOMAIN}'
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs: [{}]
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /kavita/config
      logs:
        type: emptyDir
        globalMounts:
          - path: /kavita/config/logs
      cache:
        type: emptyDir
        globalMounts:
          - path: /kavita/config/cache
      media:
        type: nfs
        server: ${NAS_IP}
        path: ${NAS_PATH}/data/ebooks/magazines
        globalMounts:
          - path: /media
            readOnly: true
