# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:xjHUXi+LChkVY6qKIAaISQXJnHCnOQ7h5mq3j6s+1rA=,iv:6yztv8htfmta6MEz+zjRZLmg4wvXwVfkRUcGtbYVJB8=,tag:ijDz88NIte9b/iYNHsBw0w==,type:str]
sops:
  age:
    - recipient: age1vpe49fq03n5atk54m4dr7h8qacpqevmcd0lzzd2jqh3rmakgwdhqtvdayn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUDVFWHp3TUJ3dlQwV0dn
        Tk1SMUwzSWFDQXNzM2h2K21VeHpwYnZDZVFRCkU1T0JMRXRnRE9PU0U3OGZUNVRP
        Um94Rkh2ZkJ2WkN3YVVPckUvakdnUHMKLS0tIENEaGs1ZVdLb2gyODFvbDl4ZUZw
        MS9EbVVEOUlPTW80bGRkOEdLeks5NGsKowV2R2zxs5eyUq3W8XaMmB5Hq5GwBuEq
        xQueKfxY7XqWan9dFf9jKzuaiyZK880boOlTzGl5w5qdyVj1YnzK0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-13T19:48:56Z"
  mac: ENC[AES256_GCM,data:M8wKghaXcWb/PF31W6NfG9ExA/hwFK9KWOmRl99/11WGQ15IVENGAauADvCUXm6MbtufUD/+SMzZ/H9uqUIOyyfBumvmx/LhJTxPz68WNkdgPdGn7VYsDgje2VUJ37vC7TPfCUZ++KkGqUO346wOo1Du0JG3qShaYt3dPBluY8E=,iv:Wd327oHVSF4/gq1I2Dkd7k6Vf2qK0J7HuOeI7PcMp7A=,tag:VN088iYIzOyMer+1q3jeKA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
