# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:2/BRM+PXEp07G8I56k7LAt3YxlK8KRCJLsFuuEVv5Z8=,iv:0sdlxAcAP9sevhtF9lChgOnSNf0Kg2s02vUalLLJ/T0=,tag:L4TTQls9BPjSBUARM8tJEw==,type:str]
sops:
  age:
    - recipient: age1vpe49fq03n5atk54m4dr7h8qacpqevmcd0lzzd2jqh3rmakgwdhqtvdayn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMno5T1NTZ3hid3pZRVNu
        UjJuY3o4d3ZqcVloemZpeVRLZERxZDJUMEJjCmplUDBtSXJwM1JJZGsxa0pGdmlo
        aW9JWTFzUlN0bnFhQVozY3NEYTVUeXMKLS0tIHNzTUczNmIwMzFyZWJhSnROOVE1
        KzJkL3lUTW1wSTZ6aWtGbFpvWEFSRWsK13PqUHU9q+gWLZqK/lTLTHo3s7AsC3AS
        /7HPHhSoDb3E2FlAh4FDbkou2SsKxQusXoD4ex7MN0blFnxkslIWxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-04T06:38:25Z"
  mac: ENC[AES256_GCM,data:4MJMt/WBiXRYPkzBP2sCskjRcdOE8gelN76IF9ly5X+4AYzwmVWNaQrfa2gzbzrvW77TTNi/Oi9W5UjzNx6yubLW8SRJCJ9yTODKqejEpO/eJlG7woBljpfha2LvrWon1MA7cvagkECYo2UarJmTkgXX1/6V+0dNt4ile5QnXoE=,iv:Ok6Ic59nRPlWlbsOelsxEDWeBiT2DNzZv/H44Zg3Y0c=,tag:JXLqNYroCBC16kTJ25l4HQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
