---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
components:
  - ../../components/common
resources:
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./maintainerr/ks.yaml
  - ./tautulli/ks.yaml
  - ./tdarr/ks.yaml
  - ./tubearchivist/ks.yaml
  - ./lidarr/ks.yaml
