---
# yaml-language-server: $schema=https://schemas.tholinka.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &app truenas
  namespace: external
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/group: Home
    gethomepage.dev/name: Truenas
    gethomepage.dev/icon: truenas.svg
    gethomepage.dev/widget.type: truenas
    gethomepage.dev/widget.url: http://${NAS_IP}
    gethomepage.dev/widget.key: '{{HOMEPAGE_VAR_TRUENAS_TOKEN}}'
spec:
  hostnames:
    - 'truenas.${SECRET_DOMAIN}'
  parentRefs:
    - name: external
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: *app
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
      timeouts:
        request: 10s
        backendRequest: 10s
