apiVersion: v1
kind: Service
metadata:
  name: immich-lb
  namespace: self-hosted
  annotations:
    lbipam.cilium.io/ips: ${CLUSTER_LB_IMMICH}
spec:
  selector:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: server
  ports:
    - port: 2283
      targetPort: 2283
  type: LoadBalancer
