apiVersion: v1
kind: Service
metadata:
  name: immich-lb
spec:
  selector:
    app: immich-server
  ports:
    - port: 2283
      targetPort: 2283
      loadBalancerIP: ${CLUSTER_LB_IMMICH}
  type: LoadBalancer
