---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tdarr-node
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions: {}
      # affinity:
      #   nodeAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 1
      #       preference:
      #         matchExpressions:
      #         # Intel N100
      #         - key: feature.node.kubernetes.io/cpu-model.id
      #           operator: In
      #           values:
      #           - "190"
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         # Intel N100
      #         - key: feature.node.kubernetes.io/cpu-model.id
      #           operator: In
      #           values:
      #           - "190"
      #         - key: intel.feature.node.kubernetes.io/gpu
      #           operator: In
      #           values:
      #           - "true"
    controllers:
      tdarr-node:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          node:
            image:
              repository: haveagitgat/tdarr_node
              tag: 2.45.01@sha256:7e98e8b97350101bda7af1673e473edd65915f10a0c5ae040487dec220a870c8
            env:
              TZ: ${TIMEZONE}
              PUID: "568"
              PGID: "1234"
              serverIP: tdarr-server.downloads.svc.cluster.local.
              serverPort: 8266
              ffmpegPath: /usr/local/bin/ffmpeg
              nodeName:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                cpu: 2
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 1234
              capabilities:
                add:
                  - CHOWN
        pod:
          nodeSelector:
            nfs-colocated: "true"
    service:
      app:
        controller: *app
        enabled: false
    persistence:
      data:
        type: nfs
        server: ${NAS_IP}
        path: ${NAS_PATH}/data
