---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app outline
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/replicas]
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: 'true'
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17
            envFrom:
              - secretRef:
                  name: *app
              - secretRef:
                  name: outline-initdb
        containers:
          app:
            image:
              repository: outlinewiki/outline
              tag: 0.86.1@sha256:57481d58bcca16493f10644b72a17c508baa7e039abf83208e182cc793525d75
            env:
              URL: https://outline.${SECRET_DOMAIN}
              PORT: &port 3000
              REDIS_URL: redis://dragonfly-cluster.database.svc.cluster.local:6379
              ENABLE_UPDATES: "false"
              OIDC_AUTH_URI: "https://auth.${SECRET_DOMAIN}/application/o/authorize/"
              OIDC_DISPLAY_NAME: Authentik
              OIDC_SCOPES: openid profile email
              OIDC_TOKEN_URI: "https://auth.${SECRET_DOMAIN}/application/o/token/"
              OIDC_USERINFO_URI: "https://auth.${SECRET_DOMAIN}/application/o/userinfo/"
              OIDC_LOGOUT_URI: "https://auth.${SECRET_DOMAIN}/application/o/outline/end-session/"
              OIDC_USERNAME_CLAIM: email
            envFrom:
              - secretRef:
                  name: *app
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 500m
                memory: 256Mi

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        annotations:
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: Home
          gethomepage.dev/name: Outline
          gethomepage.dev/icon: outline.png
          gethomepage.dev/app: *app

    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          *app :
            app:
              - path: /var/lib/outline/data
