---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app "${APP}"
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      elasticsearch:
        containers:
          app:
            image:
              repository: docker.elastic.co/elasticsearch/elasticsearch
              tag: 9.1.3
            env:
              TZ: "${TIMEZONE}"
              ES_JAVA_OPTS: -Xms8G -Xmx8G
              xpack.security.enabled: "true"
              discovery.type: single-node
              path.repo: /usr/share/elasticsearch/data/snapshot
            envFrom:
              - secretRef:
                  name: *app
            resources:
              requests:
                cpu: 1000m
                memory: 512Mi
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
              fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: elasticsearch
        ports:
          http:
            port: &port 9200
    persistence:
      data:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /usr/share/elasticsearch/data
