# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app firefly-iii
  namespace: &namespace self-hosted
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: keda
      namespace: observability
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: postgres-cluster
      namespace: database
    - name: dragonfly-cluster
      namespace: database
  components:
    - ../../../../components/common
    - ../../../../components/gatus/guarded
    - ../../../../components/gatus/internal
    - ../../../../components/volsync
  path: ./kubernetes/apps/self-hosted/firefly-iii/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false  # no flux ks dependencies
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
