---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-health-check
  namespace: network
data:
  health-check.sh: |
    #!/bin/sh
    # Health check script for Cloudflare Tunnel connectivity

    # Check if Envoy Gateway service is reachable
    if ! wget -q --timeout=10 --tries=3 -O- https://envoy-network-external-b1d9befd.network.svc.cluster.local:443 >/dev/null 2>&1; then
      echo "ERROR: Cannot reach Envoy Gateway service"
      exit 1
    fi

    # Check if Cloudflare Tunnel is connected
    if ! wget -q --timeout=10 --tries=3 -O- http://localhost:8080/ready >/dev/null 2>&1; then
      echo "ERROR: Cloudflare Tunnel not ready"
      exit 1
    fi

    echo "Health check passed"
    exit 0
