---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflare-tunnel-connectivity
  namespace: network
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflare-tunnel
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
  jobLabel: cloudflare-tunnel-connectivity
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cloudflare-tunnel-alerts
  namespace: network
spec:
  groups:
    - name: cloudflare-tunnel
      rules:
        - alert: CloudflareTunnelConnectionReset
          expr: increase(cloudflare_tunnel_connection_resets_total[5m]) > 0
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Cloudflare Tunnel connection resets detected"
            description: "Cloudflare Tunnel is experiencing connection resets to Envoy Gateway"

        - alert: CloudflareTunnelUnreachable
          expr: cloudflare_tunnel_origin_unreachable_total > 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Cloudflare Tunnel cannot reach origin service"
            description: "Cloudflare Tunnel is unable to reach the Envoy Gateway service"
