# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:vEwaLY1w0IPpwJcbgce6gAVJWokaGIAWa1R3wW2nPqNYiuAPWvV9wlPdkL5pWDPUPEWCotJ1sIkhcYB62BrJRtEp2b+CEaop7TlImsopWaef/jAB+WUmr9uN62U0WtyfXYO1GhYGLN55HYL6JEY9+O/jQd8C0JC4TgJpHe/iE4kNebsMTW3Z+Vl8vtqiYoTbZS/2ecQEeRwKH0cOi3LW52251993JxbyxrlNi6/4aakorCJu,iv:D4GI1c1yjPMVBuY8SvARW+I9yGG/eKRKurMz8K1DZsw=,tag:elSWqG6O+jyUJVxPb1xKig==,type:str]
sops:
  age:
    - recipient: age1vpe49fq03n5atk54m4dr7h8qacpqevmcd0lzzd2jqh3rmakgwdhqtvdayn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaU8rV3VYcDBwdXhjVWI4
        T3I0WHdGTHV5dlJsQlJzMkFXZnd1Z2ZoQ0NjCmI0Skdybk1OcVBXekhFcHBBbmNt
        eDNVMWlCVTJiS3RKZ1ZXTnpDYnNqZ1UKLS0tIFptU3p0NzN6ckNyeWV1WTlhcGFQ
        VGZoYXlXcWFJM21jUnlEOHZVQ1VNcWsKofgXwOwd+8YD8azmKsvzJlrcx1b6yIRD
        qZD9vd7QBoHF6JAW/kfZRLo8D0KO+cZvIRaeXI0G4aGSUiJOpLfHPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-02T15:59:05Z"
  mac: ENC[AES256_GCM,data:V5Kua+TxXH8FQNKEkmMCv2/NmrWm/VGFW4uWAFSMa3s3YOzCuZYGgIz6QMNzl8dLTpFxK27K+uV5z61vRdXQ88d/+HCL+CKh0W8LDfWD2+2PA2tgpw/kYObUgN+NkF+D7P+xILwPTRkGsosIDJEylf3rpj070FuBwSrrFd/fyG0=,iv:nn2KENPBTDKntIUTTnZhMTVY9gTx5JVXlCinWIB5Pxs=,tag:KZ/jacKWXlafK+7HAZz2zA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
