---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: self-hosted
components:
  - ../../components/common
resources:
  - ./homepage/ks.yaml
  - ./it-tools/ks.yaml
  - ./paperless/ks.yaml
  - ./immich/ks.yaml
  - ./calibre-web-automated/ks.yaml
