# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:TmQk5FPT6kDXCbFgcxhz3d3v0sXF5E4QvNUMBTjZUJ8eB6EcE7PH1Q==,iv:dnUrXPBCTsstZJP/KxtiufjYeIORAwY3+elOwEpNND0=,tag:8oBfC80uOEhsx7xHVtFyug==,type:str]
sops:
  age:
    - recipient: age1vpe49fq03n5atk54m4dr7h8qacpqevmcd0lzzd2jqh3rmakgwdhqtvdayn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvR044TDBFSDVrcVhCWWlI
        K01xVkFGMkhobWppRXE3V2lUUW5HTmpTMVFRCjcrN0htRlBick9CSFNZYzRyMFpQ
        dHg4UEcycmV0MVA2eDI2VmlSMVRTSDAKLS0tIHl1b01xVnpsYzVYR0IwUFFnMmI5
        ZXlXVTQ0ZzJuWDZ3Q0FldURsczBpRmcKUUc2Yb23uvTsUIZvHDKyGF3zSNME+QoM
        RfIBZYsnIiAi+AYyJW0l9eJREzOfUsJKFSwpWA+91W8YjWUk6VjT1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-04T06:38:25Z"
  mac: ENC[AES256_GCM,data:PG5T9L7UFy0Old1u+rLOpR7wGQzxNM8fd7ZuI4k95HJH8/YXw22w9FdxP5HMAKI5nLwVHLSCqruts7/QbZYbRqRn+c5aTKgZP3FOVv3B7xAbi4HWdNCV0PYKPDGXaJgxA9C5fPZPBYf8wb0tqQ6qpMaJBl7yHR+1Ayccb0nC5b8=,iv:+vViRxW37zQ8YB/Vku5dM7w4dF7QYAJnnGyCO3QNRNA=,tag:DbwROzpupi403ONGPivJDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
