---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: calibre-web-automated
  namespace: self-hosted
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Media
    gethomepage.dev/name: Calibre
    gethomepage.dev/icon: calibre.svg
    gethomepage.dev/app: calibre-web-automated
    gethomepage.dev/widget.type: calibreweb
    gethomepage.dev/widget.url: http://calibre-web-automated.self-hosted.svc.cluster.local:8083
    gethomepage.dev/widget.username: "{{HOMEPAGE_VAR_CALIBRE_USER}}"
    gethomepage.dev/widget.password: "{{HOMEPAGE_VAR_CALIBRE_PASS}}"
spec:
  hostnames:
    - calibre.${SECRET_DOMAIN}
  parentRefs:
    - name: internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: calibre-web-automated
          port: 8083
      timeouts:
        request: 0s
        backendRequest: 0s
      matches:
        - path:
            type: PathPrefix
            value: /
