---
# yaml-language-server: $schema=https://schemas.tholinka.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &app nextcloud
  namespace: external
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/group: Home
    gethomepage.dev/name: Nextcloud
    gethomepage.dev/icon: nextcloud.svg
    gethomepage.dev/widget.type: nextcloud
    gethomepage.dev/widget.url: https://nextcloud.${SECRET_DOMAIN}
    gethomepage.dev/widget.key: '{{HOMEPAGE_VAR_NEXTCLOUD_TOKEN}}'
spec:
  hostnames:
    - 'nextcloud.${SECRET_DOMAIN}'
  parentRefs:
    - name: external
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: *app
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
