---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: '${APP}-volsync-s3'
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: '${APP}-volsync-s3-secret'
    template:
      data:
        RESTIC_REPOSITORY: "s3:{{ .CLOUDFLARE_S3_ENDPOINT }}/volsync/${APP}"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .CLOUDFLARE_R2_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .CLOUDFLARE_R2_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: cloudflare
    - extract:
        key: volsync_template
