apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:2gdpbaUBlrFoqTRFIsgNAVa/Wg4KpuUbHYukDC0rCuD4N4E3epmSisLwBehJEVWLsy0Ex65iiCJ6bcmt0zd/6cFmShSEk6lMib4=,iv:nQbBTSDADC1S9XsZHcLRKYldPJAgZ+LZoeyBjKWtPI0=,tag:JInt+zyysCtWJXypvztOZw==,type:str]
sops:
  age:
    - recipient: age1vpe49fq03n5atk54m4dr7h8qacpqevmcd0lzzd2jqh3rmakgwdhqtvdayn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaGtvWGN6VlpwTTUzWWFy
        VFNjd2ZQVmRFVm0xQ1JEZjdPOHkwdEFSOEhzCjNIL2xWTk5sOVpIUmowUnZQTUkw
        eUZlNnpFSENLSnoyUTNtQkE3R3Y5VmcKLS0tIGNHL2MwcitRb3pKYW13aWVFblM3
        bWgzSm1URWFZWjNhRXhkbk9pOE8wUWMKrkOdxl/Yemy5ecWOasG9zfDFgOwpZYie
        YW5CKJEF3sn5G7JyVzLIwnSYc+csYJuvTghN730pJ3VZBXshMAqm0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-04T06:38:25Z"
  mac: ENC[AES256_GCM,data:O0hhMYWGjVJQI973/jYwVwgnFde+3tgMnWXZfQnObilCWMpr3PAIFzNyGEPja/Fyk8XUc0c7g90lIZrctGKJGyK1Lmr0/y8/I2tWPRLHEVYBExYyZLQq+9amJCGZ7eVN5fhVBgbav7PMoyMXVOwiHIRKdbai95RhEDUNgRLtu8Q=,iv:v1AVYlSR8CZ3gC8ZbhGlxqwILyFzfULAHT4N5uWthMQ=,tag:kD8Pn4FwJ3Qbsnk2UHxjCQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
