---
apiVersion: v1
kind: Service
metadata:
  name: &app homeassistant
  namespace: external
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ClusterIP
  ports:
    - port: 8123
      protocol: TCP
      targetPort: 8123

---
apiVersion: v1
kind: Endpoints
metadata:
  name: &app homeassistant
  namespace: external
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
subsets:
  - addresses:
      - ip: ${HOMEASSISTANT_IP}
    ports:
      - port: 8123
